config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find, only: [:show, :edit, :update, :destroy]
  def new
    @flat = Flat.new
  end

  def index
    @flats = Flat.all
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flats_path
    else
      render :edit
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

   def find
    @flat = Flat.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<%= render 'form' %>

app/views/flats/index.html.erb
  <div class="container">
                    <h1> All our flats (<%=@flats.count%>)</h1>
                    <ul> <% @flats.each do |flat|%>
                    <div class="row row-cols-1 row-cols-md-3 g-4">
                      <div class="col">
                        <div class="card h-100">
                          <img src="..." class="card-img-top" alt="...">
                          <div class="card-body">
                            <h5 class="card-title"><%= link_to flat.name, flat_path(flat) %></h5>
                            <p class="card-text">   <%= link_to flat.address, flat_path(flat) %></p>
                          </div>
                          <div class="card-footer">
                            <small class="text-muted"><%= link_to "Edit", edit_flat_path(flat)%></small>
                            <small class="text-muted"><%= link_to "Destroy", flat_path(flat), method: :delete, data: {confirm: "Are you sure? "} %></small>
                          </div>
                        </div>
                      </div>
                    </div>
  <% end %>
  </div>
<%= link_to 'New Flat', new_flat_path %>

app/views/flats/new.html.erb
<%= render 'form' %>
<hr>
<%= link_to 'Back to flats', flats_path %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<h2><%= @flat.description%></h2>
<h3><%= @flat.price_per_night%></h3>
<h4><%= @flat.number_of_guests%></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Simple AirBnb</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        <button class="btn btn-outline-primary ms-2 text-nowrap" type="submit"><%= link_to 'New Flat', new_flat_path %></button>
      </form>
    </div>
  </div>
</nav>
  <body>
    <%= yield %>
  </body>
</html>